Add required step for Percona Server repository setup with dnf
When running the current installation procedure with `dnf`, setting up the Percona Server repository fails with the following error:

```
 $ sudo percona-release setup ps-80
* Disabling all Percona Repositories
* Enabling the Percona Server for MySQL 8.0 repository
ERROR: Selected product uses "ps-80 tools" repositories. But the "tools" repository is disabled
Add "tools" repository to REPOSITORIES="" variable in /etc/default/percona-release file and re-run the script
```

An additional step is required to successfully set up the Percona Server repository:

```
echo "REPOSITORIES=\"tools\"" | sudo tee /etc/default/percona-release
```